
#' Count integrations in a genomic feature window
#'
#' This function counts the number of genomic integration sites within a specified feature window.
#'
#' @param df_sites A `data.frame` object containing genomic site information. Can come from two sources:
#' Generated by `format_aavenger_sites()` or `sample_genome()`.
#'
#' @param feature_file Path to either an `RDS` file or the path to an `RData` file containing genomic feature information.
#'
#' @param overlap_window_size The size of the window around each site where integrations will be counted.
#'
#' @return A numeric vector containing the count of integrations, total integration sites, and the percentage of integration sites.
#'
#' @examples
#' test_df <- format_aavenger_sites(unformatted_aavenger_sites) # or sample_genome()
#' test_feature_file <- readRDS('/path/to/rds)
#' test_overlap_window_size <- 10
#'
#'Call the function
#' result <- count_integrations_in_feature_window(test_df, test_feature_file, test_overlap_window_size)
#'
#' @seealso
#' \code{\link{readRDS}}, \code{\link{GenomicRanges::makeGRangesFromDataFrame}}, \code{\link{GenomicRanges::countOverlaps}}
#'
#' @import dplyr
#' @import stringr
#' @import GenomicRanges
#'
#' @export
#'
count_integrations_in_feature_window <- function(df_sites, feature_file, overlap_window_size) {

  # Check for either random or experimental sites dataframe
  if ( 'random_positions' %in% colnames(df_sites) ) {
    df_sites <- df_sites %>%
      dplyr::mutate(start = random_positions,
                    end = random_positions,
                    width = random_positions,
                    strand = '*') %>%
      dplyr::select(-random_positions)
  } else {
    if ( length(base::unique(df_sites$heatmap_group )) != 1) {
      stop('Only one heatmap group can be processed at a time')
    }
  }

  # Load feature file
  if ( stringr::str_ends(feature_file, '.rds') ) {
    epigenData <- readRDS(feature_file)
  } else {
    load(file.path(feature_file))
  }

  overlap_count_results <- GenomicRanges::countOverlaps(
    query = GenomicRanges::makeGRangesFromDataFrame(df_sites, keep.extra.columns = TRUE),
    subject = epigenData,
    maxgap = overlap_window_size/2,
    ignore.strand = TRUE)

  summed_count <- sum(overlap_count_results > 0)
  total_integration_sites <- nrow(df_sites)
  percentage_integration_sites <- 100 * (summed_count/total_integration_sites)

  return(c(summed_count, total_integration_sites, percentage_integration_sites))
}
