#' Calculate p-values for observed integration percentages in genomic features
#'
#' This function calculates p-values for observed integration percentages in genomic features based on simulated distributions.
#'
#' @param simulation_results A `data.frame` containing simulation results, including overlap window size, feature track file,
#' and simulated integration percentages. Generated by `rnorm_simulate_many_counts_in_features()` or `simulate_many_counts_in_features()`.
#'
#' @param experimental_results A `data.frame` containing experimental integration results, including overlap window size, feature track file,
#' heatmap group, and observed integration percentages. Generated by `experimental_counts_in_features()`.
#'
#' @return A `data.frame` containing observed integration percentages, corresponding probabilities from simulated distributions,
#' and two-sided p-values for each heatmap group, feature track, and overlap window size combination.
#'
#' @examples
#' # Example usage:
#' integration_percentage_in_feature_p_value(simulation_results, experimental_results)
#'
#' @import dplyr
#'
#' @export
integration_percentage_in_feature_p_value <- function(simulation_results, experimental_results) {


  if (!length(setdiff(base::unique(simulation_results$feature_track), base::unique(experimental_results$feature_track))) == 0 ) {
    stop('feature track values must match in both simulation_results and experimental_results')
  }

  if (!length(setdiff(base::unique(simulation_results$overlap_window_size), base::unique(experimental_results$overlap_window_size))) == 0 ) {
    stop('overlap_window_size values must match in both simulation_results and experimental_results')
  }

  feature_files_to_process <-  base::unique(simulation_results$feature_track)
  overlap_window_sizes <- base::unique(simulation_results$overlap_window_size)

  experimental_probabilities <- data.frame()
  for (feature_track_file in feature_files_to_process){

    print(feature_track_file)

    for (single_overlap_value in overlap_window_sizes){

      simulation_percentage_distribution <- simulation_results %>%
        dplyr::filter(
          feature_track == feature_track_file,
          overlap_window_size == single_overlap_value
        ) %>%
        dplyr::pull(percentage_integrations_in_feature)

      # Calculate the observed integration percentage probability and p-value using the simulated
      # distribution
      df_probability_subset <- experimental_results %>%
        dplyr::filter(
          feature_track == feature_track_file,
          overlap_window_size == single_overlap_value
        ) %>%
        dplyr::group_by(heatmap_group) %>%
        dplyr::mutate(
          probability = stats::ecdf(simulation_percentage_distribution)(percentage_integrations_in_feature),
          p_value = ifelse(probability > 0.5, 1 - probability, probability),
          p_value = p_value * 2,
          sd_from_mean = (percentage_integrations_in_feature - mean(simulation_percentage_distribution)) / sd(simulation_percentage_distribution)
        ) %>%
        dplyr::ungroup()

      experimental_probabilities <- rbind(experimental_probabilities, df_probability_subset)
    }
  }
  return(experimental_probabilities)
}
