#' Plot integration percentages from simulation results and experimental probabilities
#'
#' This function generates and displays histograms of integration percentages from simulation results,
#' overlaid with rectangles representing experimental integration probabilities.
#'
#' @param simulation_results A `data.frame` object containing simulation results, including overlap window size, feature track file,
#' and simulated integration percentages. Generated by `rnorm_simulate_many_counts_in_features()` or `simulate_many_counts_in_features()`
#'
#' @param experimental_probabilities A `data.frame` object containing experimental integration probabilities, including overlap window size,
#' feature track file, heatmap group, and experimental integration percentages. Generated by `experimental_counts_in_features()`.
#'
#' @param bindwidth_value The binwidth for the histogram.
#'
#' @param use_basename A logical value indicating whether to use the base name of the feature track file for plot titles (for cleaner titles).
#'
#' @return A list of ggplot objects representing the generated plots for each feature track.
#'
#' @examples
#' # Example usage:
#' plot_integration_percentages(simulation_results, experimental_probabilities, 2, TRUE)
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
#'
plot_integration_percentages <- function(simulation_results, experimental_probabilities, bindwidth_value, use_basename = TRUE) {

  plot_objects <- list()

  feature_track_list <-  base::unique(simulation_results$feature_track)

  for (feature_track_file in feature_track_list) {

    if (use_basename) {
      feature_title <- base::basename(feature_track_file)
    } else {
      feature_title <- feature_track_file
    }

    df_simulation_resultssubset <- simulation_results %>%
      dplyr::filter(feature_track == feature_track_file)

    df_experimental_probabilities_subset <- experimental_probabilities %>%
      dplyr::filter(feature_track == feature_track_file)

    p1 <- ggplot(df_simulation_resultssubset, aes(x = percentage_integrations_in_feature))+
      facet_wrap(~overlap_window_size, scales = 'free') +
      geom_histogram(binwidth = bindwidth_value, color = 'black') +
      geom_rect(data = df_experimental_probabilities_subset,
                aes(xmin = percentage_integrations_in_feature, xmax = percentage_integrations_in_feature, ymin = 0, ymax = Inf,
                    fill = heatmap_group,
                    color = heatmap_group),
                alpha = 0.5) +
      theme_classic() +
      theme(
        strip.background = element_blank(),
        strip.text = element_text(face = 'bold')
      ) +
      scale_y_continuous(expand = c(0, 0)) +
      scale_x_continuous(expand = c(0, 0)) +
      # scale_x_continuous(expand = c(0, 0), limits = c(0, 100), breaks = seq(0, 100, by = 10)) +
      labs(title = basename(feature_title), y = 'simulations', y = 'sites in feature (%)', fill = 'source') +
      guides(color = 'none')

    print(p1)

    plot_objects[[feature_track_file]] <- p1

  }

  return(plot_objects)
}

