#' Relabel Repeat Categories
#'
#' This function simplifies repeat classification labels in a data frame by categorizing various types of repeats into broader categories. The new labels are stored in a column called `repeat_simplified`.
#'
#' @param df A data frame containing a column `repeat_class`, which categorizes different types of repeats.
#' @return A data frame with an additional column `repeat_simplified`, where repeat categories are relabeled into standardized classifications:
#'   \describe{
#'     \item{LINE}{Long Interspersed Nuclear Element (LINE) repeats.}
#'     \item{SINE}{Short Interspersed Nuclear Element (SINE) repeats.}
#'     \item{LTR}{Long Terminal Repeat (LTR) elements.}
#'     \item{satellite}{Satellite repeats.}
#'     \item{retrotransposon}{Retrotransposon repeats.}
#'     \item{DNA}{DNA transposons.}
#'     \item{unknown}{Unknown repeats.}
#'     \item{RNA}{RNA-related repeats, including rRNA, snRNA, scRNA, tRNA, and srpRNA.}
#'     \item{low_complexity}{Low complexity regions.}
#'     \item{other}{Other repeat types, including RC/Helitron.}
#'     \item{simple_repeat}{Simple repeat sequences.}
#'     \item{not_a_repeat}{Entries without a repeat classification.}
#'   }
#' @details Relabels items in the column `repeat_class` generated by RepeatMasker into more simplified terms stored in `repeat_simplified`.
#' @import dplyr
#' @import stringr
#' @export
relabel_repeat_categories <- function(df) {
  df <- df %>%
    dplyr::mutate(
      repeat_simplified = ifelse(is.na(repeat_class), 'not_a_repeat', repeat_class),
      repeat_simplified = ifelse(repeat_simplified == '', 'not_a_repeat', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'LINE'), 'LINE', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'SINE'), 'SINE', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'LTR'), 'LTR', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'atellite'), 'satellite', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'etrop'), 'retrotransposon', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'DNA'), 'DNA', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'known'), 'unknown', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'rRNA|snRNA|scRNA|tRNA|srpRNA'), 'RNA', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'Low_complexity'), 'low_complexity', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'RC/Helitron'), 'other', repeat_simplified),
      repeat_simplified = ifelse(stringr::str_detect(repeat_simplified, 'Simple_repeat'), 'simple_repeat', repeat_simplified)
    )
  return(df)
}
