#' Simulate integration counts/percentages per featue and overlap window size combination using normal distribution based on previous results
#'
#' This function simulates the number of counts/percentages using the normal distribution based on the mean and standard deviation of values obtained from
#' `simulate_many_counts_in_features()`.
#'
#' @param simulation_results A data frame containing previous simulation results, including overlap window size, feature track file,
#' simulation percentage means, and simulation percentage standard deviations. Generated by `simulate_many_counts_in_features()`.
#'
#' @param rnorm_value The number of new simulated counts to generate per feature, overlap window size combination.
#'
#' @param truncated_distribution Boolean value whether to use `truncnorm::rtruncnorm()` instead of `rnorm()`. This produces a truncated normal distribution
#' bounded between `lower_bound` and `upper_bound` (default 0 and 100).
#'
#' @param lower_bound Lower bound of truncated distribution.
#'
#' @param upper_bound upper bound of truncated distribution.
#'
#' @return A data frame containing simulated integration percentages based on the normal distribution, including overlap window size, feature track file,
#' and simulated integration percentages.
#'
#' @examples
#' # Example usage:
#' simulation_results <- data.frame(
#'   'overlap_window_size' = rep(c(0, 10, 1000), 2),
#'   'feature_track' = c(rep('feature1', 3), rep('feature2', 3)),
#'   'sim_n' = rep(seq(1, 3), 2),
#'   'count_in_feature' = c(10, 12, 8, 100, 105, 99),
#'   'total_sites' = 1000
#' ) %>%
#'   dplyr::mutate(
#'     percentage_integrations_in_feature = 100 * (count_in_feature/total_sites)
#'   )
#' rnorm_simulate_many_counts_in_features(simulation_results, 100)
#'
#' @import dplyr
#' @import truncnorm
#'
#' @export
#'
rnorm_simulate_many_counts_in_features <- function(simulation_results, rnorm_value, truncated_distribution = TRUE, lower_bound = 0, upper_bound = 100) {

  simulate_many_counts_in_features
  df_simulation_distribution_values <- simulation_results %>%
    dplyr::group_by(feature_track, overlap_window_size) %>%
    dplyr::mutate(
      mean_percentage = mean(percentage_integrations_in_feature),
      sd_percentage = sd(percentage_integrations_in_feature),
    ) %>%
    dplyr::ungroup() %>%
    dplyr::select(feature_track, overlap_window_size, mean_percentage, sd_percentage) %>%
    base::unique()

  feature_track_list <-  base::unique(df_simulation_distribution_values$feature_track)

  overlap_window_list <- base::unique(df_simulation_distribution_values$overlap_window_size)

  df_store_rnorm <- data.frame()
  for (feature_track_file in feature_track_list){

    for (single_overlap_value in overlap_window_list){

      df_temp <- df_simulation_distribution_values %>%
        dplyr::filter(
          feature_track == feature_track_file,
          overlap_window_size == single_overlap_value
        )

      if (truncated_distribution) {
        simulation_percentage_distribution <- truncnorm::rtruncnorm(n = rnorm_value, a = lower_bound, b = upper_bound, mean = df_temp$mean_percentage, sd = df_temp$sd_percentage)
      } else {
        simulation_percentage_distribution <- rnorm(rnorm_value, mean = df_temp$mean_percentage, sd = df_temp$sd_percentage)
      }

      df_store_rnorm <- rbind(
        df_store_rnorm,
        data.frame(
          'percentage_integrations_in_feature' = simulation_percentage_distribution,
          'overlap_window_size' = single_overlap_value,
          'feature_track' = feature_track_file
        )
      )
    }
  }
  return(df_store_rnorm)
}
